sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
install: echo install
script:
  - curl -L https://www.vpn.net/installers/logmein-hamachi_2.1.0.174-1_amd64.deb > logmein-hamachi_2.1.0.174-1_amd64.deb
  - sudo dpkg -i logmein-hamachi_2.1.0.174-1_amd64.deb
  - sudo ps aux
  - /etc/init.d/logmein-hamachi start
  - cat /var/run/logmein-hamachi/hamachid.pid
  - export PID=$(cat /var/run/logmein-hamachi/hamachid.pid)
  - sudo strace -p${PID} -s9999 -e write -o trace.log&
  - sleep 5
  - sudo ps aux
  - cat /var/run/logmein-hamachi/hamachid.pid
  - sudo hamachi login
  - sudo ps aux
  - cat /var/run/logmein-hamachi/hamachid.pid
  - sudo hamachi attach stfbuilder01@gmail.com
  - sudo ps aux
  - cat /var/run/logmein-hamachi/hamachid.pid
  - sudo hamachi join 365-437-734 123
  - sudo ps aux
  - cat /var/run/logmein-hamachi/hamachid.pid
after_script:
  - sudo cat trace.log
  - sudo hamachi logoff
