sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
install: echo install
script:
  - curl -L https://www.vpn.net/installers/logmein-hamachi_2.1.0.174-1_amd64.deb > logmein-hamachi_2.1.0.174-1_amd64.deb
  - sudo dpkg -i logmein-hamachi_2.1.0.174-1_amd64.deb
  - sudo /etc/init.d/logmein-hamachi start
  - sudo hamachi --help
  - sudo hamachi login
  - sudo hamachi attach builder01@gmail.com
  - sudo hamachi join 365-437-734 123
after_script:
- sudo hamachi logoff
