sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
install: echo install
script:
  - sudo logmein-hamachi
  - sleep 5
  - sudo hamachi start debug
  - sudo hamachi login
  - sudo hamachi attach stfbuilder01@gmail.com
  - sudo hamachi join 365-437-734 123
after_script:
- sudo hamachi logoff
