sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
install: echo install
script:
  - if [[ "$JOB" == "1" ]]; then
      echo 'job1' &&
      curl -L https://www.vpn.net/installers/logmein-hamachi_2.1.0.174-1_amd64.deb > logmein-hamachi_2.1.0.174-1_amd64.deb &&
      sudo dpkg -i logmein-hamachi_2.1.0.174-1_amd64.deb &&
      hamachi --help &&
      hamachi login &&
      hamachi logoff &&
      hamachi attach builder01@gmail.com
      ;
    else
      echo 'job2';
    fi
env:
  global:
  - VARIABLE=value
  matrix:
  - JOB=1
  - JOB=2
